### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by FanRenLa** [MCTeamPotato/Snow-Real-Magic-Potato-Edition#1]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

snowrealmagic-1.16.5-2.10.0-1.16.5

### Modloader version

36.2.39

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/FanRenLa/49691555d09d2821a69e753e8b4363b5

### Issue description

疑似与TerraForged（版本TerraForged-1.16.5-0.2.16）有问题，导致崩溃。
https://gist.github.com/FanRenLa/49691555d09d2821a69e753e8b4363b5
https://gist.github.com/FanRenLa/97cd7a07030000b8857bede06e39582a

**Comment by FanRenLa** [comment]
第二次尝试重新创建一个世界，直接在创建时崩溃；最后删除雪！真实的魔法！（土豆版）之后顺利进入游戏，且探索一段时间没有崩溃（包括有雪的群系）。

**Comment by Kasualix** [comment]
急的话先用terraforged的0.2.12版本，我回头修。

**Comment by Kasualix** [comment]
2.10.1 fixed.
